import { ChevronRight, Copy } from "lucide-react"
import { Button } from "../ui/button"
import { useContext, useEffect, useMemo, useState } from "react"
import { WordsBlockState } from "@/lib/types"
import { generateMnemonic } from "bip39"
import { toast } from "sonner"
import { ScreenContext } from "@/context/context"

const DisplayAutoGeneratedWords = ({ setBlockState }: {
    setBlockState: (s: WordsBlockState) => void
}) => {

    const [words, setWords] = useState<string[]>([]);
    const { setScreen } = useContext(ScreenContext);


    useEffect(() => {
        const wordsStr = generateMnemonic(128);
        setWords(wordsStr.split(" "));
    }, []);

    const saveMnemonic = () => {
        localStorage.setItem("mnemonic", words.join(" "))
    }

    const copyWords = () => {
        const item = new ClipboardItem({ "text/plain": new Blob([words.join(" ")], { type: "text/plain" }) });
        navigator.clipboard.write([item]);
        toast.success("Copied all words!");
    }
    return <>
        <div className="flex items-center justify-center gap-2 mt-10">
            <h3 className="text-center text-2xl font-sans">
                Save Recovery Phrases
            </h3>
            <Copy className="size-5 text-primary cursor-pointer active:scale-[0.95]" onClick={copyWords} />
        </div>
        <div className="w-4/5 mx-auto grid grid-cols-2 sm:grid-cols-3 gap-5 mt-10" onCopy={(e) => {
            e.preventDefault();
            copyWords();
        }}>
            {
                words.length > 0 &&
                words.map((w, i) => <div key={i} className="flex gap-2 font-sans-serif shadow border border-border/30 rounded p-2">
                    <span unselectable="on" style={{ "WebkitUserSelect": "none" }} className="text-foreground/50" >{i + 1}.</span>
                    {w}
                </div>)
            }
        </div>

        {/* buttons */}
        <div className="w-4/5 mx-auto mt-10 flex flex-col md:flex-row gap-2">
            <Button variant={"outline"} className="w-full shrink" onClick={() => setBlockState("12-words")}>
                Recover Accounts
            </Button>
            <Button className="w-full shrink" onClick={() => {
                saveMnemonic();
                setScreen("password");
            }}>
                Continue
                <ChevronRight />
            </Button>
        </div>
    </>
}

export default DisplayAutoGeneratedWords