import { useState } from "react"
import { WordsBlockState } from "@/lib/types";
import Recover12Words from "./Recover12Words";
import DisplayAutoGeneratedWords from "./AutoGenerateWords";
import Recover24Words from "./Recover24Words";


const WordsBlock = () => {
    const [words, setWords] = useState<string[]>([]);
    const [blockState, setBlockState] = useState<WordsBlockState>("auto");


    return (
        <>
            <div className="w-full md:max-w-xl overflow-y-auto md:overflow-y-clip shadow bg-linear-to-br from-[#1f2029] to-accent h-full md:h-auto md:min-h-[80dvh] pt-10 md:rounded-3xl md:rounded-b-none transition-all duration-100">
                <div className="w-full flex items-center justify-center mt-15 mb-5 gap-2 group">
                    <img src="/banana.png" className="w-[50px] h-[50px] aspect-square object-contain group-hover:scale-[1.05] group-hover:rotate-10 transition-all duration-100" alt="Logo" />
                    <h1 className="text-5xl font-salsa font-semibold">Banana</h1>
                </div>
                <h2 className="text-center text-lg font-sans">Web3 HD Wallet</h2>

                {/* Words Display */}
                {
                    blockState == "auto" && <DisplayAutoGeneratedWords setBlockState={setBlockState} />
                }
                {
                    blockState == "12-words" && <Recover12Words setBlockState={setBlockState} />
                }
                {
                    blockState == "24-words" && <Recover24Words setBlockState={setBlockState} />
                }
            </div>
        </>
    )
}


export default WordsBlock   